# Generated by Django 5.2.7 on 2025-10-28 21:00

import django.db.models.deletion
from django.db import migrations, models


def create_default_category(apps, schema_editor):
    Category = apps.get_model('LittleLemonAPI', 'Category')
    # Ensure a category with id=1 exists for the FK default
    Category.objects.get_or_create(
        id=1,
        defaults={
            'slug': 'default',
            'title': 'Default',
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        # Create a default Category row that matches the FK default value
        migrations.RunPython(create_default_category, migrations.RunPython.noop),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='LittleLemonAPI.category'),
        ),
    ]
