# Generated by Django 5.2.7 on 2025-11-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0008_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_item_of_the_day',
            field=models.BooleanField(default=False, help_text='Marks this menu item as the item of the day (only one should be True)'),
        ),
    ]
